---
- apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - ntp
    - ntpdate

- name: Update /etc/timezone
  template:
    src: timezone.j2
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  notify: restart ntp

- name: Update /etc/localtime
  file:
    src: "/usr/share/zoneinfo/{{ ntp_timezone }}"
    dest: /etc/localtime
    force: yes
    owner: root
    group: root
    mode: 0644
    state: link
  notify: restart ntp

- name: Update config NTP
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify: restart ntp
